### ISSUE TITLE
About CIFAR-FS question?

### ISSUE THREAD

**Issue by 777aaa** [iCGY96/DNPG#2]
First of all, I like your DNPG work very much. I have tested the pth file you provided on three data sets, which is almost consistent with the index in your paper under other Settings. However, I have encountered some problems when testing the CIFAR-FS model you provided under 5way 5shot. According to your setting, ACC is (88.638, 0.205), but AUROC is (86.716, 0.222), which is a little different from the AUROC index in your paper is (87.90,0.13). I have some doubts about this, I hope you can answer it, thank you very much.

**Comment by zhenyuZ-HUST** [comment]
Thanks for your appreciation on our work. For the CIFAR dataset, we found that the DNPG model works best when generating 8 NPs, so pay attention to the comments in lines 198 and 240 of the AttnClassifier.py file, and modify line 243 to: fakeclass_center = torch.cat((fakeclass_center1, fakeclass_center2, fakeclass_ center3, fakeclass_center4, fakeclass_center5,fakeclass_center6, fakeclass_center7, fakeclass_center8), 1)

**Comment by 777aaa** [comment]
Thanks for your reply! I found it works!
